### ISSUE TITLE
Problem with matplotlib NavigationToolbar2QTAgg

### ISSUE THREAD

**Issue by PedroVenancio** [alexbruy/statist#2]
Hi Alexander, 

After today's or yesterday's update of matplotlib to 2.0.0-1 on OSGeo4W (64bits), statist stoped work:

Python error: Couldn't load plugin statist due to an error when calling its classFactory() method See message log (Python Error) for more details.

Couldn't load plugin statist due to an error when calling its classFactory() method 

ImportError: cannot import name NavigationToolbar2QTAgg 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/pedro/.qgis2/python/plugins\statist\__init__.py", line 77, in classFactory
    from statist import StatistPlugin
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/pedro/.qgis2/python/plugins\statist\statist.py", line 35, in 
    import statistdialog
  File "C:/OSGEO4~1/apps/qgis-rel-dev/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/pedro/.qgis2/python/plugins\statist\statistdialog.py", line 49, in 
    from matplotlib.backends.backend_qt4agg import NavigationToolbar2QTAgg as NavigationToolbar
ImportError: cannot import name NavigationToolbar2QTAgg

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.5 Las Palmas, f85ff26

**Comment by hzhu8lsu** [comment]
Broken on QGIS 2.18.6. Same issue.

**Comment by fladmas** [comment]
Broken on QGIS 2.18.7. Same issue.

**Comment by spaceof7** [comment]
Here is a workaround to get Statist working.  For whatever reason the version check isn't working so to fix this error edit line 49 of the statistdialog.py:
from:
    from matplotlib.backends.backend_qt4agg import NavigationToolbar2QTAgg as NavigationToolbar
to:
    from matplotlib.backends.backend_qt4agg import NavigationToolbar2QT as NavigationToolbar

**Comment by harisbal** [comment]
Thanks @spaceof7 . Shall we create a simple pull request maybe?

**Comment by patrice-geo** [comment]
@harisbal The code repo doesn't seem to be up-to-date...
