### ISSUE TITLE
Error Loading plugin on Windows using qgis 2.18.9

### ISSUE THREAD

**Issue by mobcdi** [alexbruy/statist#4]
When I download the plugin and install it I get the following error 
```
The plugin is broken. Python said:
2
```
I'm not sure what other information I can provide

**Comment by alexbruy** [comment]
Fixed, please redownload plugin.

**Comment by mobcdi** [comment]
Getting the error 
`The plugin is broken Pytho said
No module names qqsfieldcombobos`
