### ISSUE TITLE
Statist not available on all installs of QGIS 3

### ISSUE THREAD

**Issue by geomenke** [alexbruy/statist#5]
I've been migrating a course to QGIS 3 that uses Statist. On my windows machine I have installed Statist and it works great. However, on two of my colleagues machines (one windows, one Mac) Statist is not available, even when they enable experimental plugins. I'm wondering if one of the settings from my OsGeo4W install is allowing me, but not them, to find and install it?

**Comment by alexbruy** [comment]
Probably your colleagues have QGIS 2.99, not 3.x. Another possible reason — they don't have my repo  (https://plugins.bruy.me/plugins/plugins.xml) added to the Plugin Manager.

**Comment by geomenke** [comment]
I can confirm that they are running 3 and not 2.99. They just don't see Statist in the list of available plugins. I do, and I don't have your repo added to Plugin Manager. I'm just connected to the default QGIS  official repo [https://plugins.qgis.org/plugins/plugins.xml] Should this be available via the offical repo?

**Comment by alexbruy** [comment]
Probably you already have Statist installed, in this case it is visible in the Plugin Manager even if not available in the QGIS plugins repository.

Right now all my plugins availabale only from my own repository.

**Comment by geomenke** [comment]
OK so for me that must have been a setting imported from QGIS 2.x. Thanks!
